<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PerformanceDataUploadService" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:i0="http://www.eurodw.eu/EDServices/1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsp:Policy wsu:Id="wsHttp_PerformanceDataUploadServiceEndPoint_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <wsoma:OptimizedMimeSerialization xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"/>
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false"/>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256/>
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict/>
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp/>
          </wsp:Policy>
        </sp:TransportBinding>
        <sp:SignedSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
              <wsp:Policy>
                <sp:WssUsernameToken10/>
              </wsp:Policy>
            </sp:UsernameToken>
          </wsp:Policy>
        </sp:SignedSupportingTokens>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy/>
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens/>
            <sp:RequireClientEntropy/>
            <sp:RequireServerEntropy/>
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing/>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:import namespace="http://www.eurodw.eu/EDServices/1.0" location="PerformanceDataUploadService.wsdl"/>
  <wsdl:types/>
  <wsdl:binding name="wsHttp_PerformanceDataUploadServiceEndPoint" type="i0:IPerformanceDataUploadService">
    <wsp:PolicyReference URI="#wsHttp_PerformanceDataUploadServiceEndPoint_policy"/>
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="UploadPerformanceData">
      <soap12:operation soapAction="http://www.eurodw.eu/EDServices/1.0/IPerformanceDataUploadService/UploadPerformanceData" style="document"/>
      <wsdl:input name="UploadPerformanceDataRequest">
        <soap12:header message="i0:UploadPerformanceDataRequest_Headers" part="EDCode" use="literal"/>
        <soap12:header message="i0:UploadPerformanceDataRequest_Headers" part="PoolCutOffDate" use="literal"/>
        <soap12:header message="i0:UploadPerformanceDataRequest_Headers" part="SignatureData" use="literal"/>
        <soap12:header message="i0:UploadPerformanceDataRequest_Headers" part="UploadDate" use="literal"/>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="UploadPerformanceDataResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="EDServiceFaultFault">
        <soap12:fault name="EDServiceFaultFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PerformanceDataUploadService">
    <wsdl:port name="wsHttp_PerformanceDataUploadServiceEndPoint" binding="tns:wsHttp_PerformanceDataUploadServiceEndPoint">
      <soap12:address location="https://ut.eurodw.eu/edservices/1.0/PerformanceDataUploadService.svc"/>
      <wsa10:EndpointReference>
        <wsa10:Address>https://ut.eurodw.eu/edservices/1.0/PerformanceDataUploadService.svc</wsa10:Address>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>