//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.06 at 06:04:44 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.eurodw.eu/EDServices/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ut.eurodw.eu.edservices;
