//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.06 at 06:04:44 PM GMT 
//


package ut.eurodw.eu.edservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Filestream" type="{http://schemas.microsoft.com/Message}StreamBody"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filestream"
})
@XmlRootElement(name = "UploadPerformanceDataRequest")
public class UploadPerformanceDataRequest {

    @XmlElement(name = "Filestream", required = true)
    protected byte[] filestream;

    /**
     * Gets the value of the filestream property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFilestream() {
        return filestream;
    }

    /**
     * Sets the value of the filestream property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFilestream(byte[] value) {
        this.filestream = value;
    }

}
